export const seedMatches = [
    {
        "id": "u_11",
        "date": "2026-05-09",
        "time": "15:00",
        "opponent": "PFC Victoria Res.",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_10",
        "date": "2026-05-02",
        "time": "15:00",
        "opponent": "Harrow United",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_9",
        "date": "2026-04-25",
        "time": "15:00",
        "opponent": "Hayes & Hillingdon",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_8",
        "date": "2026-04-18",
        "time": "15:00",
        "opponent": "Kodak (Harrow)",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_7",
        "date": "2026-04-11",
        "time": "15:00",
        "opponent": "Stonewall",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_6",
        "date": "2026-04-04",
        "time": "15:00",
        "opponent": "Sporting Duet M 1st XI",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_5",
        "date": "2026-03-21",
        "time": "15:00",
        "opponent": "Stonewall",
        "isHome": true,
        "competition": "The Alec Smith Premier Cup Semi Final",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_4",
        "date": "2026-03-14",
        "time": "15:00",
        "opponent": "Larkspur Rovers",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_3",
        "date": "2026-02-21",
        "time": "15:00",
        "opponent": "Stonewall",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_2",
        "date": "2026-02-14",
        "time": "15:00",
        "opponent": "Camden & Islington United",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "u_1",
        "date": "2026-02-07",
        "time": "15:00",
        "opponent": "Eagles Land Cricklewood",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "",
        "result": "Pending"
    },
    {
        "id": "p3_9",
        "date": "2026-01-31",
        "time": "15:00",
        "opponent": "Sporting Duet M 1st XI",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "2-1",
        "result": "Loss",
        "goalscorers": "T.Siemienczuk",
        "notes": ""
    },
    {
        "id": "p3_8",
        "date": "2026-01-24",
        "time": "15:00",
        "opponent": "Larkspur Rovers",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "6-3",
        "result": "Loss",
        "goalscorers": "H.Clark, M.Hassan, M.Santana"
    },
    {
        "id": "p3_7",
        "date": "2026-01-17",
        "time": "15:00",
        "opponent": "Indian Gymkhana Club",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "4-0",
        "result": "Win",
        "goalscorers": "R.Godfrey-Brown, M.Hassan(3)"
    },
    {
        "id": "p3_6",
        "date": "2026-01-10",
        "time": "15:00",
        "opponent": "London Fennecs",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "7-0",
        "result": "Win",
        "goalscorers": "H.Bacon, F.Canlier(2), E.Feka, M.Hassan, M.Santana(2)"
    },
    {
        "id": "p3_5",
        "date": "2025-12-20",
        "time": "15:00",
        "opponent": "Eagles Land Cricklewood",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "3-0",
        "result": "Win",
        "goalscorers": "M.Hassan, M.Santana(2)"
    },
    {
        "id": "p3_4",
        "date": "2025-12-13",
        "time": "15:00",
        "opponent": "Jolof Sports",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "1-2",
        "result": "Loss",
        "goalscorers": "E.Feka"
    },
    {
        "id": "p3_3",
        "date": "2025-12-06",
        "time": "15:00",
        "opponent": "LBS Lions",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "1-1",
        "result": "Draw",
        "goalscorers": "F.Canlier"
    },
    {
        "id": "p3_2",
        "date": "2025-11-29",
        "time": "15:00",
        "opponent": "Hilltop 2nds",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "5-0",
        "result": "Win",
        "goalscorers": "A.Feka(2), E.Feka, R.Piepolli, T.Siemienczuk"
    },
    {
        "id": "p3_1",
        "date": "2025-11-22",
        "time": "15:00",
        "opponent": "Indian Gymkhana Club",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "1-6",
        "result": "Win",
        "goalscorers": "F.Canlier, H.Clark, E.Feka(2), E.Moreno, T.Siemienczuk"
    },
    {
        "id": "p2_8",
        "date": "2025-11-15",
        "time": "15:00",
        "opponent": "Sporting Duet M 1st XI",
        "isHome": false,
        "competition": "The Alec Smith Premier Cup",
        "scoreline": "1-1",
        "result": "Win",
        "goalscorers": "T.Siemienczuk",
        "notes": "Away Win on penalties"
    },
    {
        "id": "p2_7",
        "date": "2025-11-08",
        "time": "15:00",
        "opponent": "Camden & Islington United",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "3-3",
        "result": "Draw",
        "goalscorers": "E.Feka(2), S.Tahir"
    },
    {
        "id": "p2_6",
        "date": "2025-11-04",
        "time": "19:45",
        "opponent": "Brook House",
        "isHome": false,
        "competition": "Middlesex County FA Premier Cup",
        "scoreline": "7-0",
        "result": "Loss",
        "goalscorers": ""
    },
    {
        "id": "p2_5",
        "date": "2025-11-01",
        "time": "15:00",
        "opponent": "London Fennecs",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "1-0",
        "result": "Loss",
        "goalscorers": ""
    },
    {
        "id": "p2_4",
        "date": "2025-10-25",
        "time": "15:00",
        "opponent": "LBS Lions",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "4-1",
        "result": "Win",
        "goalscorers": "R.Godfrey-Brown, M.Hassan, R.Piepolli, T.Siemienczuk"
    },
    {
        "id": "p2_3",
        "date": "2025-10-18",
        "time": "15:00",
        "opponent": "Wood Lane",
        "isHome": true,
        "competition": "Premier Division",
        "scoreline": "3-1",
        "result": "Win",
        "goalscorers": "E.Feka(2), C.Noble-Cleary"
    },
    {
        "id": "p2_2",
        "date": "2025-10-04",
        "time": "15:00",
        "opponent": "LBS Lions",
        "isHome": false,
        "competition": "The Alec Smith Premier Cup",
        "scoreline": "1-4",
        "result": "Win",
        "goalscorers": "M.Hassan, B.LEE-KHAN(2), T.Siemienczuk"
    },
    {
        "id": "p2_1",
        "date": "2025-10-01",
        "time": "19:45",
        "opponent": "London Samurai Rovers",
        "isHome": true,
        "competition": "Middlesex County FA Premier Cup",
        "scoreline": "2-2",
        "result": "Win",
        "goalscorers": "R.Godfrey-Brown, B.LEE-KHAN",
        "notes": "Home Win on penalties"
    },
    {
        "id": "p1_7",
        "date": "2025-09-27",
        "time": "15:00",
        "opponent": "Hayes & Hillingdon",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "1-0",
        "result": "Loss",
        "goalscorers": ""
    },
    {
        "id": "p1_6",
        "date": "2025-09-20",
        "time": "15:00",
        "opponent": "Kensington Dragons",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "3-3",
        "result": "Draw",
        "goalscorers": "R.Godfrey-Brown, M.Hassan, A.Sengerwal"
    },
    {
        "id": "p1_5",
        "date": "2025-09-13",
        "time": "15:00",
        "opponent": "PFC Victoria Res.",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "4-4",
        "result": "Draw",
        "notes": "+2 points (Opposition deduction)",
        "goalscorers": "R.Godfrey-Brown, B.LEE-KHAN, K.Omar, O.Sufi"
    },
    {
        "id": "p1_4",
        "date": "2025-09-06",
        "time": "15:00",
        "opponent": "Jolof Sports",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "0-4",
        "result": "Win",
        "goalscorers": "E.Feka, R.Godfrey-Brown, B.LEE-KHAN, C.Noble-Cleary"
    },
    {
        "id": "p1_3",
        "date": "2025-08-30",
        "time": "15:00",
        "opponent": "Kodak (Harrow)",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "0-1",
        "result": "Win",
        "goalscorers": "B.LEE-KHAN"
    },
    {
        "id": "p1_2",
        "date": "2025-08-23",
        "time": "15:00",
        "opponent": "Harrow United",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "3-6",
        "result": "Win",
        "goalscorers": "H.Clark, M.Hassan(3), B.LEE-KHAN(2)"
    },
    {
        "id": "p1_1",
        "date": "2025-08-09",
        "time": "15:00",
        "opponent": "Wood Lane",
        "isHome": false,
        "competition": "Premier Division",
        "scoreline": "1-3",
        "result": "Win",
        "goalscorers": "M.Hassan, B.LEE-KHAN(2)"
    }
];
