ALTER TABLE players 
ADD COLUMN IF NOT EXISTS yellow_cards INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS red_cards INTEGER DEFAULT 0;

ALTER TABLE matches
ADD COLUMN IF NOT EXISTS yellow_cards TEXT,
ADD COLUMN IF NOT EXISTS red_cards TEXT;
